#Directories for neccessary files in submitting a VASP jobs. e.g. slurm.sh and vdw_kernel.bindat.
attachment_path: your-path-to-this-example/mcp/attachment
#Directory for storing the work directory.
work_dir: your-path-to-this-example/mcp/work
#Path of database for storing the mcp tool execution records.
db_path: your-path-to-this-example/mcp/record/record.db
#API key for the Materials Project.
mp_api_key: your-mp-api-key
#Directory for storing the downloaded structures.
structure_path: your-path-to-this-example/mcp/downloads
#Default INCAR settings for different VASP jobs.
VASP_default_INCAR:
  relaxation:
    NCORE: 4
    PREC: 'Accurate'
    ISMEAR: 0
    SIGMA: 0.03
    EDIFF: 1e-6
    AMIN: 0.01
    LCHARG: True
    IBRION: 1
    EDIFFG: -0.005
    NSW: 100
    MAGMOM: "5000*0"
    ISIF: 3
    NELM: 120
    LWAVE: False
    LCHARG: True
  scf_nsoc: 
    NCORE: 4
    PREC: 'Accurate'
    ISMEAR: 0
    SIGMA: 0.03
    EDIFF: 1e-7
    AMIN: 0.01
    LCHARG: True
    LWAVE: True
    NELM: 120
    MAGMOM: "5000*0"
  nscf_nsoc:
    NCORE: 4
    PREC: 'Accurate'
    ISMEAR: 0
    SIGMA: 0.03
    EDIFF: 1e-7
    AMIN: 0.01
    LCHARG: True
    LWAVE: True
    NELM: 120
    MAGMOM: "5000*0"
  scf_soc: 
    NCORE: 4
    PREC: 'Accurate'
    ISMEAR: 0
    SIGMA: 0.03
    EDIFF: 1e-7
    AMIN: 0.01
    LCHARG: True
    LWAVE: True
    LSORBIT: True
    LORBIT: 11
    NELM: 120
    MAGMOM: "5000*0"
  nscf_soc:
    NCORE: 4
    PREC: 'Accurate'
    ISMEAR: 0
    SIGMA: 0.03
    EDIFF: 1e-7
    AMIN: 0.01
    LCHARG: True
    LWAVE: True
    ICHARG: 11
    ISART: 1
    LSORBIT: True
    LORBIT: 11
    NELM: 120
    MAGMOM: "5000*0"
